# 스프링 서버 포트
server:
  port: 8082

# gRPC 서버 포트
grpc:
  server:
    port: 50052

debug: true

spring:
  datasource:
    url: ${POSTGRESQL_SOURCE_URL}
    username: ${POSTGRESQL_SOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration